# Generated by Django 5.2.4 on 2025-07-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_teacher_name_teacher_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qualification'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Experience (years)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Incharge', 'Incharge'), ('DI', 'DI'), ('Teacher', 'Teacher'), ('Other', 'Other')], default='Teacher', max_length=30),
        ),
    ]
