# Generated by Django 5.2.4 on 2025-07-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_education_teacher_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='custom_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Custom Position (if Other)'),
        ),
    ]
