# Generated by Django 5.2.4 on 2025-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacher_custom_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('important', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/attachments/')),
            ],
        ),
    ]
