# Generated by Django 5.2.4 on 2025-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('Exam', 'Exam'), ('Holiday', 'Holiday'), ('Announcement', 'Announcement'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
