# Generated by Django 5.2.4 on 2025-07-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notice_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
    ]
