# Generated by Django 5.2.4 on 2025-07-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_result_marks_subjectresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresult',
            name='practical_grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='practical_grade_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='practical_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='theory_grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='theory_grade_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='theory_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
