# Generated by Django 5.2.4 on 2025-07-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_subjectresult_practical_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectresult',
            name='final_grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='grade_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='practical_grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='theory_grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
