# Generated by Django 5.2.4 on 2025-07-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_leadershipmessage'),
        ('core', '0018_studentaccount'),
    ]

    operations = [
    ]
