# Generated by Django 5.2.4 on 2025-07-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
