# Generated by Django 5.2.4 on 2025-07-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_teacher_user_teacher_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=50, unique=True, null=True), # Allow null temporarily
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
