# Generated by Django 5.2.4 on 2025-07-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
