# Generated by Django 5.2.4 on 2025-07-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_post_postcomment_question_answer_statusupdate_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/covers/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/covers/'),
        ),
    ]
