# Generated by Django 5.2.4 on 2025-07-27 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_result_gpa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('credit_hour', models.FloatField(default=1.0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gallerylike',
            unique_together={('gallery', 'user', 'session_key', 'ip_address')},
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Mid Term', 'Mid Term'), ('Final Term', 'Final Term'), ('Unit Test', 'Unit Test'), ('Pre-Board', 'Pre-Board'), ('Board Exam', 'Board Exam'), ('Other', 'Other')], default='Final Term', max_length=50)),
                ('academic_year', models.CharField(default='2024-25', max_length=20)),
                ('theory_marks', models.FloatField(blank=True, null=True)),
                ('theory_total', models.FloatField(default=100, help_text='Total marks for theory')),
                ('practical_marks', models.FloatField(blank=True, null=True)),
                ('practical_total', models.FloatField(default=0, help_text='Total marks for practical')),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_point', models.FloatField(blank=True, null=True)),
                ('is_passed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.subject')),
            ],
            options={
                'ordering': ['student__full_name', 'subject__name'],
                'unique_together': {('student', 'subject', 'exam_type', 'academic_year')},
            },
        ),
    ]
