# Generated by Django 5.2.4 on 2025-07-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_subject_leadershipmessage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('credit_hour', models.FloatField(default=1.0)),
                ('theory_full_marks', models.FloatField(default=100.0, help_text='Total marks for theory')),
                ('theory_pass_marks', models.FloatField(default=40.0, help_text='Pass marks for theory')),
                ('practical_full_marks', models.FloatField(default=0.0, help_text='Total marks for practical')),
                ('practical_pass_marks', models.FloatField(default=0.0, help_text='Pass marks for practical')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of subjects in the class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='core.subject')),
            ],
            options={
                'verbose_name': 'Class Subject',
                'verbose_name_plural': 'Class Subjects',
                'ordering': ['class_name', 'order', 'subject__name'],
                'unique_together': {('class_name', 'subject')},
            },
        ),
    ]
