# Generated by Django 5.2.4 on 2025-07-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_classsubject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassSubject',
        ),
    ]
