# Generated by Django 5.2.4 on 2025-08-10 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_attendancereport_qrsession_qrcodelog_qrattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='qrattendance',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='qrattendance',
            name='session',
        ),
        migrations.RemoveField(
            model_name='qrattendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='qrcodelog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='qrcodelog',
            name='student',
        ),
        migrations.RemoveField(
            model_name='qrsession',
            name='class_section',
        ),
        migrations.RemoveField(
            model_name='qrsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='qrsession',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='qrsession',
            name='teacher',
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.CharField(help_text='Google Sheet ID', max_length=100)),
                ('sheet_name', models.CharField(help_text='Name of the Google Sheet', max_length=200)),
                ('exam_type', models.CharField(choices=[('Mid Term', 'Mid Term'), ('Final Term', 'Final Term'), ('Unit Test', 'Unit Test'), ('Pre-Board', 'Pre-Board'), ('Board Exam', 'Board Exam'), ('Other', 'Other')], max_length=50)),
                ('academic_year', models.CharField(default='2024-25', max_length=20)),
                ('range_read', models.CharField(default='Sheet1!A2:H', help_text='Range read from sheet', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
        migrations.DeleteModel(
            name='QRAttendance',
        ),
        migrations.DeleteModel(
            name='QRCodeLog',
        ),
        migrations.DeleteModel(
            name='QRSession',
        ),
    ]
