# Generated by Django 5.2.4 on 2025-08-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_aboutpage_achievement_banner_contactinfo_corevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
