# Generated by Django 5.2.4 on 2025-08-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_notice_is_active'),
    ]

    operations = [
    ]
