from django.urls import path
from . import views
from .views import teacher_login_view, teacher_dashboard_view, post_homework_view, view_submissions_view, logout_view, public_profile_view

urlpatterns = [
    # HTML page routes
    path('', views.index_page, name='index'),
    path('faculty/', views.faculty_page, name='faculty'),
    path('gallery/', views.gallery_page, name='gallery'),
    path('gallery/upload/', views.gallery_upload, name='gallery_upload'),
    path('about/', views.about_page, name='about'),
    path('contact/', views.contact_page, name='contact'),
    path('homework/', views.homework_page, name='homework'),
    path('library/', views.library_page, name='library'),
    path('notices/', views.notices_page, name='notices'),
    path('notes/', views.notes_page, name='notes'),
    path('results/', views.results_page, name='results'),
    path('student-signup/', views.student_signup_page, name='student_signup_page'),
    path('login/', views.login_page, name='login_page'),
    path('student-dashboard/', views.student_dashboard, name='student_dashboard'),
    path('dashboard/', views.unified_dashboard_view, name='dashboard'),
    path('feed/', views.student_feed, name='student_feed'),
    path('profile/', views.profile_page, name='profile_page'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('my-details/', views.my_details_view, name='my_details'),
    path('profile/<str:username>/', public_profile_view, name='public_profile'),
    # Remove student-account-login and teacher/login/
    # path('student-account-login/', views.student_account_login, name='student_account_login'),
    # path('teacher/login/', teacher_login_view, name='teacher_login'),
    # API endpoints
    path('api/teachers/', views.TeacherList.as_view()),
    path('api/gallery/', views.GalleryList.as_view()),
    path('api/homework/', views.HomeworkList.as_view()),
    path('api/contact/', views.ContactMessageCreate.as_view()),
    path('api/results/', views.ResultSearch.as_view()),
    
    # Website Content API endpoints
    path('api/about/', views.views_website_content.AboutPageAPIView.as_view(), name='api_about'),
    path('api/core-values/', views.views_website_content.CoreValueListAPIView.as_view(), name='api_core_values'),
    path('api/achievements/', views.views_website_content.AchievementListAPIView.as_view(), name='api_achievements'),
    path('api/contact-info/', views.views_website_content.ContactInfoAPIView.as_view(), name='api_contact_info'),
    path('api/social-media/', views.views_website_content.SocialMediaListAPIView.as_view(), name='api_social_media'),
    path('api/facilities/', views.views_website_content.FacilityListAPIView.as_view(), name='api_facilities'),
    path('api/banners/', views.views_website_content.BannerListAPIView.as_view(), name='api_banners'),
    path('api/welcome-messages/', views.views_website_content.WelcomeMessageListAPIView.as_view(), name='api_welcome_messages'),
    path('api/school-info/', views.views_website_content.SchoolInfoAPIView.as_view(), name='api_school_info'),
    path('api/results/analytics/', views.ResultAnalyticsView.as_view(), name='result_analytics'),
    path('api/results/subject-performance/', views.SubjectPerformanceView.as_view(), name='subject_performance'),
    path('api/results/student-history/', views.StudentPerformanceHistoryView.as_view(), name='student_performance_history'),
    path('api/results/templates/', views.ResultTemplateView.as_view(), name='result_templates'),
    path('api/results/grade-scales/', views.GradeScaleView.as_view(), name='grade_scales'),
    path('api/results/import/', views.import_results_excel, name='import_results_excel'),
    path('api/results/export/', views.export_results_excel, name='export_results_excel'),
    path('api/results/bulk-save/', views.bulk_save_results, name='bulk_save_results'),
    path('api/results/delete/', views.delete_result, name='delete_result'),
    path('api/notices/', views.NoticeList.as_view()),
    path('api/resources/', views.ResourceList.as_view(), name='resource_list'),
    path('api/students/', views.StudentListCreate.as_view()),
    path('api/students/<int:pk>/', views.StudentRetrieveUpdateDestroy.as_view()),
    path('api/student-signup/', views.StudentSignup.as_view()),
    path('api/login/', views.LoginView.as_view()),
    path('api/logout/', views.LogoutView.as_view()),
    path('api/register/', views.RegisterView.as_view()),
    path('api/user-role/', views.UserRoleView.as_view()),
    path('api/all-students/', views.StudentListAll.as_view()),
    path('api/all-teachers/', views.TeacherListAll.as_view()),
    path('api/homework-due-today/', views.HomeworkDueTodayView.as_view()),
    path('api/recent-submissions/', views.RecentSubmissionsView.as_view()),
    path('api/submit-homework/', views.HomeworkSubmissionCreateView.as_view()),
    path('api/activity-log/', views.ActivityLogView.as_view()),
    path('api/gallery/<int:pk>/likes/', views.gallery_likes_api, name='gallery_likes_api'),
    path('api/gallery/<int:pk>/comments/', views.gallery_comments_api, name='gallery_comments_api'),
    path('api/post/<int:pk>/like/', views.post_like_api, name='post_like_api'),
    path('api/post/<int:pk>/comments/', views.post_comments_api, name='post_comments_api'),
    path('api/status/<int:pk>/like/', views.status_like_api, name='status_like_api'),
    path('api/status/<int:pk>/comments/', views.status_comments_api, name='status_comments_api'),
    path('api/status/<int:pk>/delete/', views.delete_status_api, name='delete_status_api'),
    path('api/comment/<int:comment_id>/delete/', views.delete_comment_api, name='delete_comment_api'),
    path('api/homework/<int:homework_id>/delete/', views.delete_homework_api, name='delete_homework_api'),
    path('api/follow/<str:username>/', views.follow_user_api, name='follow_user_api'),
    path('api/toggle-follow/', views.toggle_follow_api, name='toggle_follow_api'),
    path('api/friend-suggestions/', views.friend_suggestions_api, name='friend_suggestions_api'),
    path('api/search-friends/', views.search_friends_api, name='search_friends_api'),
    path('profile/<str:username>/', views.view_profile, name='view_profile'),
    path('api/next-symbol-number/', views.next_symbol_number_api, name='next_symbol_number_api'),
    
    # Enhanced Result Management API endpoints
    path('api/subjects/', views.SubjectListCreate.as_view(), name='subject_list_create'),
    path('api/subjects/<int:pk>/', views.SubjectRetrieveUpdateDestroy.as_view(), name='subject_retrieve_update_destroy'),
    path('api/marks/', views.MarksListCreate.as_view(), name='marks_list_create'),
    path('api/marks/<int:pk>/', views.MarksRetrieveUpdateDestroy.as_view(), name='marks_retrieve_update_destroy'),
    path('api/student-result/<str:symbol_number>/', views.student_result_api, name='student_result_api'),
    path('api/add-subject/', views.add_subject_api, name='add_subject_api'),
    path('api/add-student/', views.add_student_api, name='add_student_api'),
    path('api/submit-marks/', views.submit_marks_api, name='submit_marks_api'),
    
    # New API endpoints for enhanced result management
    path('api/subjects/search/', views.subjects_search_api, name='subjects_search_api'),
    path('api/students/search/', views.students_search_api, name='students_search_api'),
    path('api/marks/auto-save/', views.marks_auto_save_api, name='marks_auto_save_api'),
    path('api/subjects/<int:subject_id>/marks/', views.subject_marks_api, name='subject_marks_api'),
    path('api/generate-symbol-number/', views.generate_numeric_symbol_number_api, name='generate_numeric_symbol_number_api'),
    path('api/email-students-list/', views.email_students_list_api, name='email_students_list_api'),
    path('api/send-result-email/<str:symbol_number>/', views.send_result_notification_email, name='send_result_notification_email'),
    
    # Enhanced Marks Entry System URLs
    path('api/students/search-enhanced/', views.StudentSearchView.as_view(), name='student_search_enhanced'),
    path('api/subjects/marks/', views.SubjectMarksView.as_view(), name='subject_marks'),
    path('api/results/enhanced/', views.EnhancedResultView.as_view(), name='enhanced_results'),
    path('api/marks/enhanced-bulk-save/', views.enhanced_bulk_save_marks, name='enhanced_bulk_save_marks'),
    path('api/subjects/for-class/', views.get_subjects_for_class, name='get_subjects_for_class'),
    path('api/subjects/set-for-class/', views.set_subjects_for_class, name='set_subjects_for_class'),
    path('api/marks/progress/', views.get_marks_entry_progress, name='get_marks_entry_progress'),
    

]

urlpatterns += [
    path('attendance/', views.attendance_overview_view, name='attendance_overview'),
    path('teacher/dashboard/', teacher_dashboard_view, name='teacher_dashboard'),
    path('teacher/post-homework/', post_homework_view, name='post_homework'),
    path('teacher/submissions/', view_submissions_view, name='view_submissions'),
    path('logout/', logout_view, name='logout'),
    path('api/teacher-dashboard/', views.teacher_dashboard_api, name='teacher_dashboard_api'),
    path('teacher-dashboard/', views.teacher_dashboard_view, name='teacher_dashboard'),
    path('teacher-login/', views.teacher_login_view, name='teacher_login'),
]